spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-club-db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true