version: '2'

services:
  app:
    image: 'fitness-club-app:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongo_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fitness-club-db
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017

  mongo_db:
    image: "mongo:4.4.3"
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=fitness-club-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres